### ISSUE TITLE
License 

### ISSUE THREAD

**Issue by hungaroring** [djordjened92/yudo#1]
Hi djordjened92,

congratulations on your excellent result, it's a real breakthrough in the field of oriented objects detection, which until now has been dominated by algorithms that find only rotated bounding box and not the direction. Would you mind adding any open source license to your code so that more researchers can legally use your work in their experiments?

**Comment by hungaroring** [comment]
And, by the way, do you consider contributing your work to the [mmrotate repository](https://github.com/open-mmlab/mmrotate)?

**Comment by djordjened92** [comment]
Hi @hungaroring,

thank you, I'm glad that this work caught your attention. The only reason for the license absence is that I missed adding it :smile: Since my codebase is mainly from [yolov7](https://github.com/WongKinYiu/yolov7), I've just added the same GNU General Public License v3.0.
Regarding contributing YUDO to the mmrotate, to be honest,  I haven't considered this so far.  I'd need to see what effort is necessary to put there, but yes it would be very nice to have it there.

**Comment by hungaroring** [comment]
Thanks a lot!
